name: Build and Deploy to SiteGround

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install & Build
        run: |
          npm ci
          npm run build

      - name: Add SG host to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "$SG_PORT" "$SG_HOST" >> ~/.ssh/known_hosts
        env:
          SG_HOST: ${{ secrets.SG_HOST }}
          SG_PORT: ${{ secrets.SG_PORT }}

      - name: Configure SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy via rsync
        run: |
          rsync -az --delete \
            --exclude='.well-known' \
            dist/ ${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:${{ secrets.SG_REMOTE_PATH }}
        env:
          SG_HOST: ${{ secrets.SG_HOST }}
          SG_USER: ${{ secrets.SG_USER }}
          SG_REMOTE_PATH: ${{ secrets.SG_REMOTE_PATH }}
          
